package com.example.e5322.thyrosoft.Activity;

public class MessageConstants {
    public static String ENTER_MOBILE = "Please enter mobile number";
    public static String ENTER_NAME = "Please enter name";
    public static String ENTER_FNAME = "Please enter first name";
    public static String ENTER_MNAME = "Please enter middle name";
    public static String ENTER_LNAME = "Please enter last name";
    public static String ENTER_ADDRESS = "Please enter address";
    public static String ENTER_EMAIL = "Please enter email ID";
    public static String ENTER_AGE = "Please enter age";
    public static String ENTER_PINCODE = "Please enter pincode";
    public static String ENTER_VALID_MOBILE = "Please enter valid mobile number";
    public static String MOBILE_10_DIGITS = "Mobile number should be of 10 digits";
    public static String VALID_EMAIL = "Please enter valid Email Id";
    public static String ADDRESS_MIN_25 = "Address should be minimum of 25 characters";
    public static String ADDRESS_MAX_250 = "Address should be maximum of 250 characters";
    public static String PASSWORD_MIN_6 = "Password should be minimum of 6 characters";
    public static String PASSWORD_MAX_20 = "Password should be maximum of 20 characters";
    public static String PINCODE_6_DIGITS = "Pincode should be of 6 digits";
    public static String Kdly_entee_emaliID = "Kindly enter valid email ID";
    public static String APP_NOT_AVAILABLE = "No App Available";
    public static String FILE_DOWN_SUCCSS = "File download successfully..";

    public static String DOC_SUCC = "Document uploaded successfully";
    public static String VERIFY = "Verify otp first";
    public static String PLEASEENTERSCANOPINION = "Please enter Scan Opinion";
    public static String PLEASEENTERCLINICALOPINION = "Please enter Clinical Opinion";
    public static String CHECKING_UPDATE_PLEASE_WAIT = "Checking for update. Please wait..";
    public static String PLEASE_WAIT = "Please wait..";
    public static String CHECK_INTERNET_CONN = "Check your internet connection";
    public static String SOMETHING_WENT_WRONG = "Something went wrong. Please try after sometime";
    public static String OTP_GEN_SUCCESS = "OTP generated Successfully";
    public static String TOKEN_NOT_FOUND = "Token not found";
    public static CharSequence AUTH_FAILED = "Authorization has been denied for this request.";
    public static String PRICEERROR = "NHF rate is zero";
    public static String NODATA = "No Data Available";
    public static String WHATSAPP_NOT_INSTALLED = "WhatsApp not installed";
    public static String BAKTOST = "Kindly click on reset button to back";
    public static String MOBILE_NO_USED_10_TIMES = "This mobile number is already referred for more than 10 times in last 90 days.Kindly enter another mobile number.";
    public static String MSG_SHOULD_NOT_START_SPACE = "Message should not start with space";
    public static String REMARKS_SHOULD_NOT_START_SPECIAL_CHAR = "Remarks should not contain special character at the beginning.";
    public static String REMARKS_SHOULD_NOT_START_4_TIMES = "Remarks should not contain a character more than 4 times in a row.";
    public static String THANK_YOU_FEEDBACK = "Thank you for your valuable information!";
    public static String FEEDBACK_SUCCESS = "Feedback Submitted Successfully";
    public static String ENTER_AMOUNT = "Please enter amount to add in your account";
    public static String REMARKS_SHOULD_NOT_START_SPACE = "Remarks should not start with space";
    public static String INVALID_EMAIL = "Invalid email ID";
    public static String ABSURD_VALUE = "Absurd Value. Redo and Re enter";
}
